default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: test_app_development
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: <%= ENV['DATABASE'] || 'test_app_test' %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

