development:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  adapter: postgresql
  encoding: unicode
  database: test_app_development
  pool: 5
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

test:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE'] || 'test_app_test' %>
  pool: 5
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

<<: *default
  url: <%= ENV['DATABASE_URL'] %>
